spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.239.229:3306/blog?characterEncoding=utf-8&useSSL=false
    username: worker
    password: Work111111~
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log



